name: Windows
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '15 12 * * 0'

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_KEY }}
  AWS_DEFAULT_REGION: us-west-2

jobs:
  build:
    name: ${{ matrix.configuration }}-${{ matrix.platform }}-build
    runs-on: windows-2019
    strategy:
      matrix:
        platform: [x64]
        configuration: [Release]
      fail-fast: false
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Download OpenCppCoverage
        uses: suisei-cn/actions-download-file@v1
        if: success() && matrix.platform == 'x64'
        id: DownloadOpenCppCoverage
        with:
          url: "https://opencppcoverage.gallerycdn.vsassets.io/extensions/opencppcoverage/opencppcoverageplugin/0.9.7.1/1581265346391/OpenCppCoverage-0.9.7.1.vsix"
          target: ${{ github.workspace }}\temp\

      - name: Unzip OpenCppCoverage
        if: success() && matrix.platform == 'x64'
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: ${{ github.workspace }}\temp\OpenCppCoverage-0.9.7.1.vsix
          pathTarget: ${{ github.workspace }}\temp\OpenCppCoverage

      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v1

      - name: Check if build is running from origin repo
        if: ${{ success() && env.AWS_ACCESS_KEY_ID != 0 && env.AWS_SECRET_ACCESS_KEY != 0 }}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws,s3://vcpkg.cache.boinc/,readwrite" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Check if build is running from fork
        if: ${{ success() && (env.AWS_ACCESS_KEY_ID == 0 || env.AWS_SECRET_ACCESS_KEY == 0) }}
        run: |
          echo "VCPKG_BINARY_SOURCES=clear;x-aws-config,no-sign-request;x-aws,s3://vcpkg.cache.boinc/,read" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append

      - name: Fix vcpkg
        run: vcpkg.exe integrate remove

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}\3rdParty\Windows\cuda\
          key: windows-${{ matrix.platform }}-${{ matrix.configuration }}-${{ hashFiles('win_build/vcpkg_3rdparty_dependencies_vs2019.vcxproj', '.github/workflows/windows.yml') }}

      - name: Build
        run: msbuild win_build\boinc_vs2019.sln -p:Configuration=${{ matrix.configuration }} -p:Platform=${{ matrix.platform }} -p:VcpkgTripletConfig=ci -p:BuildConfig=ci -m

      - name: Run tests
        if: success() && matrix.platform == 'x64'
        working-directory: win_build\Build\${{ matrix.platform }}\${{ matrix.configuration }}
        run: ${{ github.workspace }}\temp\OpenCppCoverage\OpenCppCoverage-x64\OpenCppCoverage.exe --cover_children --optimized_build --sources ${{ github.workspace }} --export_type=cobertura:cobertura.xml -- unittests.exe --gtest_output=xml:gtest.xml

      - name: Prepare logs on failure
        if: ${{ failure() }}
        run: |
          7z.exe a -t7z -mx=9 deploy/logs.7z -r0 3rdParty/Windows/vcpkg/buildtrees/*.log

      - name: Upload logs on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: windows_logs_${{ matrix.type }}_${{ github.event.pull_request.head.sha }}
          path: deploy/logs.7z

      - name: Prepare artifacts for deploy
        if: ${{ success() }}
        shell: cmd
        run: |
          python deploy\prepare_deployment.py win_apps
          python deploy\prepare_deployment.py win_client
          python deploy\prepare_deployment.py win_manager

      - name: Upload apps
        uses: actions/upload-artifact@v2
        with:
          name: win_apps_${{ matrix.platform }}_${{ github.event.pull_request.head.sha }}
          path: deploy/win_apps.7z

      - name: Upload client
        uses: actions/upload-artifact@v2
        with:
          name: win_client_${{ matrix.platform }}_${{ github.event.pull_request.head.sha }}
          path: deploy/win_client.7z

      - name: Upload manager
        uses: actions/upload-artifact@v2
        with:
          name: win_manager_${{ matrix.platform }}_${{ github.event.pull_request.head.sha }}
          path: deploy/win_manager.7z

      - name: Upload symbol files
        uses: actions/upload-artifact@v2
        with:
          name: win_pdb_${{ matrix.platform }}_${{ github.event.pull_request.head.sha }}
          path: win_build/Build/${{ matrix.platform }}/${{ matrix.configuration }}/*.pdb

      - name: Upload Google Tests Results
        if: always() && matrix.platform == 'x64'
        uses: actions/upload-artifact@v2
        with:
          name: Windows_tests_results
          path: "win_build/Build/${{ matrix.platform }}/${{ matrix.configuration }}/**/gtest.xml"

      - name: Upload coverage report
        if: success() && matrix.platform == 'x64'
        run: |
          curl -Os https://uploader.codecov.io/latest/windows/codecov.exe
          chmod +x codecov.exe
          ./codecov.exe
